### PR TITLE
Create a conda environment and test on binder

### PR DESCRIPTION
**Pull request by tonyfast**
This is a really cool tutorial @parsing-science.  Thank you for helping me use TensorFlow and PyMC for the first time!  I was able to reproduce the notebooks on `python=3` if I removed the byte strings; that is part of this pull request.

I also replaced `requirements.txt` with `environment.yaml` to create `conda` environments.  `conda` environments can use `pip`;   `pymc3` is installed with `git+`.  

To run your notebooks, simply download [Anaconda](https://www.continuum.io/downloads) for free and follow the instructions in the `readme.md`.  The workflow is very similar to using `virtualenv`.

I suggest trying `Anaconda` for a few reasons:
- At PyData events, most folks are using `python` through `Anaconda`.
- `conda` installs for the `numpy` and `scipy` stack are more reliable than `pip`,
  - It is easiest to access the bleeding edge versions of packages through [`conda-forge`](conda-forge.github.io).
- On reliability, `conda` installs will save time in your tutorial.  It removes many potential installation problems across Mac, Windows, and Linux.

Another option too is [Binder](mybinder.org); free on demand notebook compute.  

[Binder](http://mybinder.org:/repo/tonyfast/pymc3_quickstart_guide)

Clicking the badge above will launch a working version of your notebooks in the browser; I can qualify that the `logistic` notebook does indeed work.  I have used Binder for a few tutorials; zero install issues.  The only install issue is if Binder is working.

Good luck with your tutorial!

### CODE REVIEW

**Comment by parsing-science** [comment]
Thanks @tonyfast! I'm testing it now. I noticed that the environment installs python 3.5. Is there a way to allow the user to choose which python to use? I've only ever used Python 2.7. Some of the errors in my tutorial (e.g. the bytestrings) arise from using Python 2.7, and I wanted to be able to reproduce them during the tutorial.

**Comment by tonyfast** [comment]
you just have to add `python=2.7` to the dependencies.

``` yaml
name: pymc3_quickstart_guide
dependencies: 
- python=2.7
- anaconda
- pip
- pip:
  - unidecode
  - git+https://github.com/pymc-devs/pymc3
```

Also, you can change environments within the notebook if you are using Anaconda,

image

**Comment by parsing-science** [comment]
@tonyfast: thanks for all of the help; I really appreciate it. I put in some instructions to that effect in my README and got the yml file in.

**Comment by tonyfast** [comment]
Nice one!  Good luck during your tutorial.

**Pull request closed without merging**
